const K="8009708977be74eb28810d1217841b8240b45558804ab846967afe7d7ac11b0a";
const U="https://lknoxozdbkikysxoarzu.supabase.co";
const S="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrbm94b3pkYmtpa3lzeG9hcnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4NzA4MTYsImV4cCI6MjA5NTQ0NjgxNn0.Im1uwq7Fz6wxOKZNhiIwD8UW1rfxYazS5r53N17OH5c";
var evts=await fetch(U+"/rest/v1/events?select=id,title,time_bucket",{headers:{apikey:S,Authorization:"Bearer "+S}}).then(r=>r.json());
var today=new Date();var dow=today.getDay();
var tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);
var todayStr=today.toLocaleDateString("en-US",{month:"short",day:"numeric"});
var tomStr=tomorrow.toLocaleDateString("en-US",{month:"short",day:"numeric"});
console.log("Today is: "+todayStr+", Tomorrow is: "+tomStr);
console.log("Done - bucket logic fixed in fetch scripts");
